- name: containerd install
  hosts: master, worker
  become: yes
  tasks:
  - name: docker prerequirement install
    apt:
      name:
        - ca-certificates
        - curl
        - gnupg
  - name: Add Docker GPG apt Key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present
  - name: Add Docker Repository
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu focal stable
      state: present
  - name: apt install containerd
    apt:
      name:
      - containerd.io
  - name: get cni plugins
    get_url:
      url: https://github.com/containernetworking/plugins/releases/download/v1.3.0/cni-plugins-linux-amd64-v1.3.0.tgz
      dest: /home/ansible/cni-plugins-linux-amd64-v1.3.0.tgz
  - name: mkdir cni plugins directory
    file:
      path: /opt/cni/bin
      state: directory
  - name: install cni plugins
    unarchive:
      src: /home/ansible/cni-plugins-linux-amd64-v1.3.0.tgz
      dest: /opt/cni/bin
      remote_src: yes
  - name: nerdctl download
    get_url:
      url: https://github.com/containerd/nerdctl/releases/download/v1.5.0/nerdctl-1.5.0-linux-amd64.tar.gz
      dest: /home/ansible/nerdctl-1.5.0-linux-amd64.tar.gz
  - name: install nerdctl
    unarchive:
      src: /home/ansible/nerdctl-1.5.0-linux-amd64.tar.gz
      dest: /usr/local/bin/
      remote_src: yes
  - name: generate config.toml
    shell: containerd config default > /etc/containerd/config.toml
  - name: config for systemd cgroup driver
    command: sed -i "s/SystemdCgroup = false/SystemdCgroup = true/" /etc/containerd/config.toml
  - name: systemd restart containerd
    systemd:
      state: restarted
      daemon_reload: true
      name: containerd
