- hosts: master, worker
  become: yes
  tasks:
    - name: install prerequirements
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
        update_cache: yes
    - name: add apt key for google repos
      apt_key:
        url: https://dl.k8s.io/apt/doc/apt-key.gpg
        keyring: /etc/apt/keyrings/kubernetes-archive-keyring.gpg
        state: present
    - name: add google repos to apt sources
      apt_repository:
        repo: deb [signed-by=/etc/apt/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main
        state: present
    - name: apt install kubernetes
      apt:
        name:
          - kubelet
          - kubeadm
          - kubectl
        update_cache: yes
    - name: apt mark hold kubelet
      dpkg_selections:
        name: kubelet
        selection: hold
    - name: apt mark hold kubeadm
      dpkg_selections:
        name: kubeadm
        selection: hold
    - name: apt mark hold kubectl
      dpkg_selections:
        name: kubectl
        selection: hold
