- hosts: worker
  become: yes
  tasks:
    - name: create print join command
      shell: kubeadm token create --print-join-command
      register: kubeadm_join_cmd
      delegate_to: k8s-master1.local
    - name: join node
      command: "{{ kubeadm_join_cmd.stdout }}"

